[build]
  command = "cd /opt/build/repo && pnpm install && cd packages/auth && PRISMA_CLI_BINARY_TARGETS=rhel-openssl-3.0.x,rhel-openssl-1.0.x PRISMA_LOG_QUERIES=true DATABASE_URL=$DATABASE_URL_SITE1 npx prisma generate --schema=prisma/schema.prisma && ls -l node_modules/.prisma/client/ || { echo 'No binary in auth'; exit 1; } && cd ../site1 && PRISMA_CLI_BINARY_TARGETS=rhel-openssl-3.0.x,rhel-openssl-1.0.x PRISMA_LOG_QUERIES=true DATABASE_URL=$DATABASE_URL_SITE1 npx prisma generate --schema=prisma/schema.prisma && ls -l node_modules/.prisma/client/ || { echo 'No binary in site1'; exit 1; } && pnpm --filter @my-project/site1 build && mkdir -p .netlify/functions-internal/prisma/client && cp -r ../auth/node_modules/.prisma/client/* .netlify/functions-internal/prisma/client/ && cp ../auth/dist/functions/trpc.js .netlify/functions-internal/trpc.js && ls -l .netlify/functions-internal/prisma/client/ || { echo 'No files in .netlify/functions-internal/prisma/client/'; exit 1; }"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_LOG_LEVEL = "debug"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-3.0.x,rhel-openssl-1.0.x"
  PRISMA_LOG_QUERIES = "true"
  VITE_TRPC_URL = "/trpc"

[dev]
  command = "pnpm --filter @my-project/site1 dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  functions = ".netlify/functions-internal"
  functionsPort = 8888
  autoLaunch = true

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = [
    ".netlify/functions-internal/trpc.js",
    ".netlify/functions-internal/prisma/client/**"
  ]