[build]
  functions = "dist/functions"

[dev]
  functions = "dist/functions"
  functionsPort = 8888

[functions]
  node_bundler = "esbuild"
  included_files = [
    "dist/functions/trpc.js",
    "dist/functions/prisma/client/**"
  ]
  
[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200