[build]
  command = "pnpm --filter @my-project/site2 prisma && pnpm --filter @my-project/site2 build && mkdir -p .netlify/functions-internal/prisma/client && if [ -f ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node ]; then cp ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/prisma/client/; else echo \"Warning: Prisma query engine binary not found in auth\"; fi && cp ../auth/dist/functions/trpc.js .netlify/functions-internal/trpc.js"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  DATABASE_URL = "postgresql://postgres:olvw-wudfnhu-vwdjlqj-ghy@db.asqrqvtpkudjalnjwmbb.supabase.co:5432/postgres"
  NODE_VERSION = "18"
  PRISMA_LOG_LEVEL = "debug"
  PRISMA_GENERATE_BINARY_TARGET = "rhel-openssl-3.0.x"

[dev]
  command = "pnpm --filter @my-project/site2 dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  functions = ".netlify/functions-internal"
  functionsPort = 8888
  autoLaunch = true

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = [
    ".netlify/functions-internal/trpc.js",
    ".netlify/functions-internal/prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node"
  ]