[build]
  command = "pnpm --filter @my-project/auth prisma && pnpm --filter @my-project/site2 prisma && pnpm --filter @my-project/site2 build && mkdir -p .netlify/functions-internal/prisma/client && if [ -f ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node ]; then cp ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node .netlify/functions-internal/prisma/client/ && cp ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/prisma/client/; else cp ../auth/dist/functions/prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node .netlify/functions-internal/prisma/client/ && cp ../auth/dist/functions/prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/prisma/client/ 2>/dev/null || echo \"Warning: Prisma query engine binary not found\"; fi && cp ../auth/dist/functions/trpc.js .netlify/functions-internal/trpc.js"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"
  VITE_TRPC_URL = "/trpc"

[dev]
  command = "pnpm --filter @my-project/site2 dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  functions = ".netlify/functions-internal"
  functionsPort = 8888
  autoLaunch = true

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = [
    ".netlify/functions-internal/trpc.js",
    ".netlify/functions-internal/prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node",
    ".netlify/functions-internal/prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node"
  ]