[build]
  command = "pnpm install && PRISMA_CLI_BINARY_TARGETS=rhel-openssl-3.0.x DATABASE_URL=$DATABASE_URL npx prisma generate && echo 'Generated Prisma Client in site1' && ls -l node_modules/.prisma/client/ || echo 'No binary in site1' && pnpm --filter @my-project/auth prisma && echo 'Generated Prisma Client in auth' && ls -l ../auth/node_modules/.prisma/client/ || echo 'No binary in auth' && pnpm --filter @my-project/site1 build && mkdir -p .netlify/functions-internal/prisma/client && if [ -f node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node ]; then cp node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/prisma/client/ && cp node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/ && echo 'Copied binary from site1'; elif [ -f ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node ]; then cp ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/prisma/client/ && cp ../auth/node_modules/.prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/ && echo 'Copied binary from auth'; else echo 'Warning: Prisma query engine binary not found - downloading fallback' && curl -L https://github.com/prisma/prisma-engines/releases/download/5.22.0/libquery_engine-rhel-openssl-3.0.x.so.node -o .netlify/functions-internal/prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node && cp .netlify/functions-internal/prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node .netlify/functions-internal/ && echo 'Downloaded and copied fallback binary'; fi && cp ../auth/dist/functions/trpc.js .netlify/functions-internal/trpc.js && echo 'Build completed'"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  DATABASE_URL = "postgresql://postgres:zhljkw-wudfnhu-vwdjlqj-ghy@db.frujfirwqiddeicvtjha.supabase.co:5432/postgres"
  NODE_VERSION = "18"
  PRISMA_LOG_LEVEL = "debug"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-3.0.x"

[dev]
  command = "pnpm --filter @my-project/site1 dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  functions = ".netlify/functions-internal"
  functionsPort = 8888
  autoLaunch = true

[[redirects]]
  from = "/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = [
    ".netlify/functions-internal/trpc.js",
    ".netlify/functions-internal/prisma/client/libquery_engine-rhel-openssl-3.0.x.so.node",
    ".netlify/functions-internal/libquery_engine-rhel-openssl-3.0.x.so.node"
  ]